### ISSUE TITLE
thank you for release code!

### ISSUE THREAD

**Issue by nullarch** [InstantID/InstantID#19]
I got nice result from InstantID

I want to know how to swap face like this link

https://github.com/InstantID/InstantID/raw/main/assets/compare-b.png

thank you!

**Comment by hben35096** [comment]
Successfully installed, works very well, thank you

**Comment by simonmaris** [comment]
I created a conda environment, and then followed the repo / used infer.py

For reference, here is an example `environment.yml`. CUDA is present on the system. 

```yml
name: instantID
dependencies:
  - python = 3.11
  - pip
  # - ipykernel # optional, used for jupyter kernel discovery.
  - pip:
    - opencv-python
    - transformers 
    - accelerate
    - insightface
    - diffusers
    - onnxruntime
```
